version: '3.8'
services:
  service-redis-auth:
    image: redis:7
    container_name: db-redis-auth
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gnss-auth-subnet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  service-postgres-user:
    image: "postgres:14"
    container_name: db-postgres-user
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD}
    volumes:
      - type: bind
        source: ~/postgres-migrations/user/initdb.sql
        target: /docker-entrypoint-initdb.d/migration_a.sql
      - type: bind
        source: ~/postgres-data
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER_USER} -d ${POSTGRES_USER_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gnss-user-subnet

  gnss-api-gateway:
    image: gateway-image:latest
    container_name: gateway
    ports:
      - "8000:8000"
    # healthcheck:
    #   test: ["CMD", "curl", "--fail", "--silent", "--show-error", "--output", "/dev/null", "http://localhost:8000/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    networks:
      - gnss-radar-net

  gnss-auth:
    image: auth-image:latest
    container_name: auth
    depends_on:
      service-redis-auth:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:8001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
      start_interval: 5s
    networks:
      - gnss-radar-net
      - gnss-auth-subnet

  gnss-user:
    image: user-image:latest
    container_name: user
    environment:
      PG_ADDR: ${DATABASE_USER_URL}
    depends_on:
      service-postgres-user:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:8002"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
      start_interval: 5s
    networks:
      - gnss-radar-net
      - gnss-user-subnet

networks:
  gnss-radar-net:
    driver: bridge
    external: true
  gnss-user-subnet:
    driver: bridge
  gnss-auth-subnet:
    driver: bridge
