allow_methods:
  - post
  - get
  - delete
  - put
  - options
  - patch
allow_credentials: true
allow_headers:
  - X-Csrf-Token
  - credentials
  - content-type
allow_origins:
  - http://localhost:8080
