package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"

	"github.com/Gokert/gnss-radar/internal/pkg/model"
)

// Errors is the resolver for the errors field.
func (r *queryResolver) Errors(ctx context.Context) ([]*model.Error, error) {
	res := make([]*model.Error, len(model.AllError))
	for idx, e := range model.AllError {
		elem := e
		res[idx] = &elem
	}

	return res, nil
}
