name: CICD_python

on:
  push:
    paths:
      - 'gnss-satellites/app/**'
      - '.github/workflows/python_ci.yaml'

env:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install Ruff
        run: pip install ruff
        
      - name: Run Ruff
        run: ruff check ./gnss-satellites/
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
        
      - name: Setup
        working-directory: ./gnss-satellites
        run: make setup

      - name: Run
        working-directory: ./gnss-satellites
        run: make run