name: CICD_python

on:
  push:
    paths:
      - 'gnss-satellites/app/**'

env:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Ruff
        run: ruff check ./gnss-satellites/
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup
        run: make setup

      - name: Run
        run: make run